docs_dir: docs/
repo_name: 'NCEMS/pre-summit-foss'
repo_url: 'https://github.com/NCEMS/pre-summit-foss'

site_name: 'NCEMS Pre-Summit Open Science Training'
site_description: 'Workshop teaching researchers core skills for conducting open science.'
site_author: 'Tyson Swetnam, Nicole Lazar'
site_url: 'https://ncems.github.io/pre-summit-foss'

edit_uri: edit/mkdocs/docs

# Copyright
copyright: 'Copyright &copy; 2024 The Pennsylvania State University'

# Navigation Page

nav:
  - Home: 
    - 'Home': index.md
    - 'Prerequisites': installation.md
    - 'Schedule': schedule.md
    - 'Code of Conduct': code_of_conduct.md
    - 'Glossary & Acronyms': glossary.md
  - Lessons:
    - '1. Open Science': 01_intro_open_sci.md
    - '2. Data Management': 02_managing_data.md
    - '3. Project Management': 03_project_management.md
    - '4. How to Talk to Computers': 04_talk_to_computer.md


# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: material
# setting features for the navigation tab
  features:
    - navigation.instant
      #- navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: ncems
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Regular
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  favicon: assets/favicon.ico
  icon:
    logo: material/molecule

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ncems/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
